apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "graph-db-migrater.fullname" . }}-configmap
  labels:
    {{- include "graph-db-migrater.labels" . | nindent 4 }}
    {{- if ne .Values.ciEnv "" }}
    environment: {{ .Values.ciEnv }}
    {{- end }}
data:
  {{- range $key, $value := .Values.configmap }}
  dwh_graph_db_migrater_{{ $key }}: {{ $value | quote }}
  {{- end }}