apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graph-db-migrater.fullname" . }}-secret
  labels:
    {{- include "graph-db-migrater.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque