FROM python:3.9-alpine
WORKDIR /app
COPY .ci/requirements-migrations.txt /app/requirements.txt
RUN apk add g++ python3-dev libpq-dev
RUN pip install --no-cache-dir -r requirements.txt
COPY migrations /app/migrations
COPY alembic.ini /app/alembic.ini
COPY migration_service /app/migration_service
COPY .ci/create_db_and_migrate.py /app/create_db_and_migrate.py
CMD ["python", "/app/create_db_and_migrate.py"]