"""added schema

Revision ID: 752a712e6f9e
Revises: 93fc8a0c5e6d
Create Date: 2023-05-23 11:58:42.083984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752a712e6f9e'
down_revision = '93fc8a0c5e6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('migration_guid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=110), nullable=False),
    sa.ForeignKeyConstraint(['migration_guid'], ['migrations.guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tables', sa.Column('schema_id', sa.BigInteger(), nullable=True))
    op.add_column('tables', sa.Column('db', sa.String(length=110), nullable=False))
    op.drop_constraint('tables_migration_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'schemas', ['schema_id'], ['id'])
    op.drop_column('tables', 'migration_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('migration_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_foreign_key('tables_migration_id_fkey', 'tables', 'migrations', ['migration_id'], ['id'])
    op.drop_column('tables', 'db')
    op.drop_column('tables', 'schema_id')
    op.drop_table('schemas')
    # ### end Alembic commands ###
