"""initial

Revision ID: 93fc8a0c5e6d
Revises: 
Create Date: 2023-04-04 10:06:39.245749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fc8a0c5e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=110), nullable=False),
    sa.Column('db_source', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migrations_guid'), 'migrations', ['guid'], unique=True)
    op.create_table('tables',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('migration_id', sa.BigInteger(), nullable=True),
    sa.Column('old_name', sa.String(length=110), nullable=True),
    sa.Column('new_name', sa.String(length=110), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.BigInteger(), nullable=True),
    sa.Column('old_name', sa.String(length=110), nullable=True),
    sa.Column('new_name', sa.String(length=110), nullable=True),
    sa.Column('old_type', sa.String(length=36), nullable=True),
    sa.Column('new_type', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    op.drop_table('tables')
    op.drop_index(op.f('ix_migrations_guid'), table_name='migrations')
    op.drop_table('migrations')
    # ### end Alembic commands ###
