"""added is_key field to fields table

Revision ID: c389266bedf6
Revises: 752a712e6f9e
Create Date: 2023-05-29 16:39:55.763501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c389266bedf6'
down_revision = '752a712e6f9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('is_key', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'is_key')
    # ### end Alembic commands ###
